name = "kiwibot"
main = "src/index.js"
compatibility_date = "2026-08-07"

[vars]
ROOT_ADMIN_ID = "7224762410"

[[durable_objects.bindings]]
name = "KIWI_STATE"
class_name = "KiwiState"

[[migrations]]
tag = "v1"
new_classes = [ "KiwiState" ]
