export const QUIZ_QUESTIONS = [
  {
    id: 1,
    question: "What is the first step in identifying an arbitrage opportunity?",
    correctAnswer: "Compare prices across platforms",
    acceptedAnswers: ["compare prices across platforms", "compare prices", "compare across platforms"],
    points: 1,
    category: "Trading Strategy",
    difficulty: "easy",
    source: "Trading Fundamentals",
    explanation: "You must first compare prices across different platforms to identify a price discrepancy.",
    number: 1,
  },
  {
    id: 2,
    question: "Which factor affects the net profit from a trade the most?",
    correctAnswer: "Transaction fees",
    acceptedAnswers: ["transaction fees", "fees", "fee"],
    points: 1,
    category: "Trading Costs",
    difficulty: "easy",
    source: "Trading Fundamentals",
    explanation: "Transaction fees directly reduce net profit from each trade.",
    number: 2,
  },
  {
    id: 3,
    question: "What should you verify before executing a trade?",
    correctAnswer: "All of the above",
    acceptedAnswers: ["all of the above", "all of the above", "all"],
    points: 1,
    category: "Risk Management",
    difficulty: "medium",
    source: "Trading Fundamentals",
    explanation: "Verify the seller's reputation, current price, and fees before executing.",
    number: 3,
  },
  {
    id: 4,
    question: "What does 'spread' mean in trading?",
    correctAnswer: "The difference between buy and sell price",
    acceptedAnswers: ["the difference between buy and sell price", "difference between buy and sell price", "spread", "buy sell difference"],
    points: 1,
    category: "Market Basics",
    difficulty: "easy",
    source: "Trading Fundamentals",
    explanation: "The spread is the difference between the bid and ask price.",
    number: 4,
  },
  {
    id: 5,
    question: "What's the most important risk to consider in arbitrage?",
    correctAnswer: "Price changes during the trade",
    acceptedAnswers: ["price changes during the trade", "price changes", "price change", "slippage", "timing risk", "timing"],
    points: 2,
    category: "Risk Management",
    difficulty: "hard",
    source: "Trading Fundamentals",
    explanation: "Price changes during the trade can eliminate arbitrage profits.",
    number: 5,
  },
  {
    id: 6,
    question: "What is the primary purpose of a stop-loss order?",
    correctAnswer: "Limit potential losses",
    acceptedAnswers: ["limit potential losses", "limit losses", "reduce losses", "cap losses"],
    points: 1,
    category: "Risk Management",
    difficulty: "easy",
    source: "Trading Fundamentals",
    explanation: "A stop-loss order limits potential losses by automatically closing a position at a set price.",
    number: 6,
  },
  {
    id: 7,
    question: "In which type of trading does the market typically have the highest liquidity?",
    correctAnswer: "Forex",
    acceptedAnswers: ["forex", "foreign exchange", "fx"],
    points: 1,
    category: "Market Basics",
    difficulty: "medium",
    source: "Trading Fundamentals",
    explanation: "The Forex market is the most liquid market in the world.",
    number: 7,
  },
  {
    id: 8,
    question: "What does 'leverage' mean in trading?",
    correctAnswer: "Borrowing funds to increase position size",
    acceptedAnswers: ["borrowing funds to increase position size", "borrowing funds", "borrowing to increase position", "using borrowed money"],
    points: 2,
    category: "Trading Strategy",
    difficulty: "medium",
    source: "Trading Fundamentals",
    explanation: "Leverage allows traders to control larger positions with borrowed funds.",
    number: 8,
  },
  {
    id: 9,
    question: "What is the name of the analysis that studies historical price data?",
    correctAnswer: "Technical analysis",
    acceptedAnswers: ["technical analysis", "technical"],
    points: 1,
    category: "Analysis Methods",
    difficulty: "easy",
    source: "Trading Fundamentals",
    explanation: "Technical analysis studies historical price data to identify trends and patterns.",
    number: 9,
  },
  {
    id: 10,
    question: "What does ROI stand for in trading and investing?",
    correctAnswer: "Return on Investment",
    acceptedAnswers: ["return on investment", "return on investment"],
    points: 1,
    category: "Financial Metrics",
    difficulty: "easy",
    source: "Trading Fundamentals",
    explanation: "ROI measures the profitability of an investment relative to its cost.",
    number: 10,
  },
];

export function getQuestionById(id) {
  return QUIZ_QUESTIONS.find((q) => q.id === id) || null;
}

export function getQuestionByNumber(number) {
  return QUIZ_QUESTIONS.find((q) => q.number === number) || null;
}

export const QUESTION_COUNT = QUIZ_QUESTIONS.length;
